[gulp]
path = 'C:\\Users\\Anton\\Desktop\\Chemistry\\gulp-6.0\\Exe\\gulp.exe'
[gulp.options]
xtol = 12
time = 50
[model]
bounds = 'D:\\Anton\\QMdata\\Bandura_Grant_EZFF\\HfS2\\GT_HfS2\\New\\variable_bounds_HfS2_fixed_new.txt'
template = 'D:\\Anton\\QMdata\\Bandura_Grant_EZFF\\HfS2\\GT_HfS2\\New\\template_HfS2_fixed_new.txt'
[model.structures]
[model.structures.1T_WS2]
gulp_structure = 'test_files/WS2_2H.cif'
energy = -13.4567
kpoints_index = [[0.0, 0.0, 0.0], [0.0, 0.0, 0.5], [0.5, 0.0, 0.0]]
kpoints_values = [[0, 0, 0, 27.4, 27.4, 45], [19.0, 19.0, 19.0, 19.0], [158.6, 158.6, 160.6, 160.6]]
elastic_index = [[1, 1], [3, 3], [4, 4]]
elastic_values = [262.0, 53.0, 13.0]
bulk_index = [2]
bulk_values = [63.0]
youngs_index = [1, 2, 3]
youngs_values = [248.0, 248.0, 52.0]
[model.pipeline]
[model.pipeline.1]
type="MOO"
name = "DE"
population = 500
gen = 300
[model.pipeline.2]
type="SOO"
name = "simpleGD"
template = 'D:\\Anton\\QMdata\\Bandura_Grant_EZFF\\HfS2\\GT_HfS2\\New\\template_HfS2_fixed_new.txt'